apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-and-deploy-unsigned
  namespace: demo-sign
  labels:
    tekton.dev/pipeline: build-and-deploy-unsigned
spec:
  params:
    - name: deployment-name
      value: pipelines-vote-api
    - name: git-url
      value: 'https://github.com/openshift/pipelines-vote-api.git'
    - name: git-revision
      value: master
    - name: IMAGE
      value: 'quay.io/rcarrata/pipelines-vote-api:unsigned-devconf'
    - name: namespace
      value: demo-sign
  pipelineRef:
    name: build-and-deploy-unsigned
  podTemplate:
    securityContext:
      fsGroup: 65532
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
